[feat #23] 마이페이지 조회 API 구현
TeamPophory/pophory-server pull request #27
Opened 2023-07-01 18:33 UTC by yungu0010

## 🍃 관련이슈

- Resolved: #23

## 🌱 변경사항
- 마이페이지 조회 API를 구현했습니다.

## 🌷 참고사항
- 조언해주신대로 사진의 개수를 구하는 역할은 getPhotoCount에서, 사진 정보를 가져오는 역할은 getPhotos라는 메소드에서 할 수 있도록 구현했습니다!

<img width="831" alt="image" src="https://github.com/TeamPophory/pophory-server/assets/65678579/d8bab44c-cbfb-4548-9ad7-a2d5255a7fb3">

2023-07-01 18:40 UTC, unanchoi requested changes
review 남겼습니다! 고민해보시면 좋을 것 같습니다

2023-07-01 18:40 UTC, unanchoi commented on src/main/java/com/pophory/pophoryserver/domain/member/MemberService.java
> +        return PhotoListGetResponseDto.of(photoList);
이렇게 되면, 같은 query를 2번 날리게 되서, `albumJpaRepository.findAllByMemberId(memberId)` 이 부분을 method로 만들어서 사용하시는 방법이 좋을 것 같습니다!

2023-07-01 19:35 UTC, yungu0010 commented on src/main/java/com/pophory/pophoryserver/domain/member/MemberService.java
> +        return PhotoListGetResponseDto.of(photoList);
오 그렇네요 분리해서 다시 올리겠습니당!

2023-07-02 01:13 UTC, unanchoi approved these changes
Very Very Good

2023-07-02 01:17 UTC, merged